
from torch.optim import Adam
from torch import nn
import torch
from torch.utils.data import DataLoader
from attention_vae import AttentionVAE
from pandas_dataset import CustomDataset
import matplotlib.pyplot as plt

import numpy as np

from tqdm import tqdm
import pandas as pd


def loss_function(x, x_hat, mean, log_var):
    reproduction_loss = nn.functional.binary_cross_entropy(x_hat, x, reduction='sum')
    KLD  = - 0.5 * torch.sum(1+ log_var - mean.pow(2) - log_var.exp())
    return reproduction_loss + KLD

def vae_loss(x, x_hat, mean, log_var):
    reproduction_loss = l2_loss(x, x_hat)
    KLD = - 0.5 * torch.sum(1+ log_var - mean.pow(2) - log_var.exp())
    return reproduction_loss + KLD

def l2_loss(x, x_hat):
    sq_error = (x-x_hat)**2
    sq_error = sq_error.sum(-1).sum(-1).sum(-1)
    return sq_error

def vae_loss(x, x_hat, mean, log_var):
    reproduction_loss = l2_loss(x, x_hat)
    KLD = - 0.5 * torch.sum(1+ log_var - mean.pow(2) - log_var.exp())
    return reproduction_loss + 0.01 * KLD



def train():

    # Model Hyperparameters

    dataset_path = '~/datasets'

    cuda = True
    DEVICE = torch.device("cuda" if cuda else "cpu")
    torch.set_default_device('cpu')

    chkpoint = 99
    save_plot = 10

    #todo: overwrite dims
    batch_size = 1
    x_dim = 784
    hidden_dim = 540
    latent_dim = 2

    num_csvs = 1
    df_list = []
    for i in range(num_csvs):
        df = pd.read_csv(f"/home/jupyter/racecar_gym/thesis_examples/csv_files/0425/Episode{i}")
        df = df.head(2000)
        df_list.append(df)
    train_dataset = CustomDataset(df_list)
    test_dataset = CustomDataset(df_list)

    model = AttentionVAE(sequence_length=train_dataset.sequence_length,
                         num_agents=train_dataset.num_agents,
                         latent_dim=latent_dim,
                         embedding_dim=hidden_dim)

    lr = 1e-3

    epochs = 500

    kwargs = {'num_workers': 1, 'pin_memory': True}

    # TODO


    # TRAJECTORY format should be [batch_size, num_agents, timesteps, spatial_dim (=2)]
    train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True, **kwargs)
    test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False, **kwargs)
    BCE_loss = nn.BCELoss()

    optimizer = Adam(model.parameters(), lr=lr)

    print("Start training VAE...")
    model.train()
    loss_plot = []

    for epoch in range(epochs):
        overall_loss = 0
        for batch_idx, x in enumerate(train_loader):

            #print("x ", x.size(), x)

            optimizer.zero_grad()

            x_hat, mean, log_var, z = model(x)
            loss = vae_loss(x[..., :2], x_hat, mean, log_var).mean()

            overall_loss += loss.item()

            loss.backward()
            optimizer.step()

        batch_idx += 1

        print("\tEpoch", epoch + 1, "complete!", "\tAverage Loss: ", overall_loss / (batch_idx * batch_size))
        
        loss_plot.append(overall_loss / (batch_idx * batch_size))
        
        #saving models
        if epoch % chkpoint == 0 or epoch == 999:
             if epoch > 0:
                plt.figure()
                plt.plot(np.arange(epoch+1),loss_plot,color = 'k')
                plt.xlabel("Epoch")
                plt.ylabel("Average Reconstruction Loss")
                plt.title("Average Reconstruction Loss for a Variational Autoencoder")
                plt.savefig("/home/jupyter/racecar_gym/thesis_examples/VAE_losses/Loss{}.png".format(epoch))
        
        if epoch % chkpoint == 0 or epoch == 999:
            torch.save(model,"/home/jupyter/VAEmodels/1csv_2dim_KL/model{}.pt".format(epoch))
            sample = model.sample(1,torch.device('cpu'))
            sample = sample.reshape(-1, model.num_agents, model.sequence_length, 3)
            plot_traj(sample,model,epoch)
            
            

    print("Finish!!")
    #print(loss_plot)
    

    return model, test_loader


# x is the sample trajectories or original trajectories in the format generated by tensor's dataloader
def plot_traj(x,model,epoch):
    
    #make this a scatter plot
    #color code the agents by type in some way --> Green, Yellow (orange), Red
    
    x_vals = []
    y_vals = []

    for i in range(model.num_agents):
        #print("this is a matrix!")
        #(print(x[0,0])) #--> gets the first matrix
        #print(x[0,0,1]) #--> gets the first row
        #print(x[0,0,:,0]) # --> gets the all rows in the first col

        x_vals.append(x[0,i,:,0].detach().numpy()) #append x and y trajectories for each agent
        y_vals.append(x[0,i,:,1].detach().numpy())

        #print(x_vals[0])

    #print(x_vals[0].numpy().size)
    #x_vals[0] = x_vals[0].numpy()
    #y_vals[0] = y_vals[0].numpy()
    plt.figure()
    plt.plot(x_vals[0], y_vals[0],x_vals[1],y_vals[1],x_vals[2],y_vals[2],x_vals[3],y_vals[3],
            x_vals[4],y_vals[4],x_vals[5],y_vals[5])
    plt.xlabel("x Position")
    plt.ylabel("Y Position")
    plt.title("VAE Generated Trajectories for Agents After {} Epoch(s)".format(epoch+1))
    plt.legend(["Agent A", "Agent B", "Agent C", "Agent D","Agent E","Agent F"], loc = "upper left")
    plt.show()
    plt.savefig('VAE_gen_traj{}.png'.format(epoch))

    return x_vals,y_vals




def get_test():
    
    #todo: overwrite dims
    batch_size = 1
    x_dim = 784
    hidden_dim = 540
    latent_dim = 2
    
    kwargs = {'num_workers': 1, 'pin_memory': True}
    
    num_csvs = 1
    df_list = []
    for i in range(num_csvs):
        df = pd.read_csv(f"/home/jupyter/racecar_gym/thesis_examples/csv_files/0425/Episode{i}")
        df = df.head(2000)
        df_list.append(df)
    train_dataset = CustomDataset(df_list)
    test_dataset = CustomDataset(df_list)
    
    # TRAJECTORY format should be [batch_size, num_agents, timesteps, spatial_dim (=2)]
    train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True, **kwargs)
    test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False, **kwargs)
    BCE_loss = nn.BCELoss()
    
    return test_loader





if __name__ == "__main__":
    model, test_loader = train()
    #model = torch.load("/home/jupyter/VAEmodels/model25.pt")
    #sample = model.sample(1,torch.device('cpu'))
    #for batch_idx, x in enumerate(test_loader):
        #result, mu, log_var = model(x)
    test_loader = get_test()
    
    for batch in test_loader:
        break
    
    recon, mu, log_var = model.forward(batch)
    
    plot_traj(recon,model,99)
    plot_traj(batch,model,1000000)
    
    sample = model.sample(1,torch.device('cpu'))
    sample = sample.reshape(-1, model.num_agents, model.sequence_length, 3)

    #plot original trajectories
    plot_traj(sample,model,500000)
    

    #gather the relevant information (x,y values for now)




